name: CI

permissions:
  actions: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Pinned toolchain for linting
  ACTION_LINTS_TOOLCHAIN: 1.58.1
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  CI: 1
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  build-test:
    name: Build+Test
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 20
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Compile (no features)
        run: cargo test --no-run
      - name: Compile (all features)
        run: cargo test --no-run --all-features
      - name: Test
        run: cargo test --all-features -- --nocapture --quiet
      - name: Checkout ostree-rs-ext
        uses: actions/checkout@v3
        with:
          repository: ostreedev/ostree-rs-ext
          path: ostree-rs-ext
          fetch-depth: 20
      - name: Test ostree-rs-ext
        run: ./ci/test-ostree-rs-ext.sh
  build-minimum-toolchain:
    name: "Build, minimum supported toolchain (MSRV)"
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Detect crate MSRV
        shell: bash
        run: |
          msrv=$(cargo metadata --format-version 1 --no-deps | \
              jq -r '.packages | .[0].rust_version')
          echo "Crate MSRV: $msrv"
          echo "ACTION_MSRV_TOOLCHAIN=$msrv" >> $GITHUB_ENV
      - name: Remove system Rust toolchain
        run: dnf remove -y rust cargo
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env['ACTION_MSRV_TOOLCHAIN']  }}
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: msrv
      - name: cargo check
        run: cargo check
  linting:
    name: "Lints, pinned toolchain"
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Remove system Rust toolchain
        run: dnf remove -y rust cargo
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env['ACTION_LINTS_TOOLCHAIN']  }}
          components: rustfmt, clippy
      - name: cargo fmt (check)
        run: cargo fmt -- --check -l
      - name: cargo clippy (warnings)
        run: cargo clippy -- -D warnings
